WebApplication13/Controllers/RolesController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication13.Models;

namespace WebApplication13.Controllers
{
    public class RolesController : Controller
    {
        private ApplicationDbContext context = new ApplicationDbContext();
        // GET: RolYönetimi
        public ActionResult Index()
        {
            return View(context.Roles.ToList());
        }

        public ActionResult Create()
        {


            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                context.Roles.Add(new IdentityRole()
                {
                    Name = collection["RoleName"]
                });
                context.SaveChanges();
                ViewBag.ResultMessage = "Role created successfully !";
                return View("Create");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(string RoleName)
        {
            var thisRole = context.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(thisRole);
            context.SaveChanges();
            return RedirectToAction("Create");
        }

        // GET: /Roles/Edit/5
        public ActionResult Edit(string roleName)
        {
            var thisRole = context.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            return View(thisRole);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(IdentityRole role)
        {
            try
            {
                context.Entry(role).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ManageUserRoles()
        {
            // prepopulat roles for the view dropdown
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr =>

            new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;
            return View();
        }


        public ActionResult ManageUsers()
        {
            // prepopulat roles for the view dropdown
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr =>
            new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RoleAddToUser(string UserName, string RoleName)
        {
            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context));
            manager.AddToRole(user.Id, RoleName);

            //ViewBag.ResultMessage = "Role created successfully !";

            // prepopulat roles for the view dropdown
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;

            return View("ManageUsers");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetRoles(string UserName)
        {
            if (!string.IsNullOrWhiteSpace(UserName))
            {
                ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
                var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context));

                ViewBag.RolesForThisUser = manager.GetRoles(user.Id);

                // prepopulat roles for the view dropdown
                var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
                ViewBag.Roles = list;
            }

            return View("ManageUsers");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRoleForUser(string UserName, string RoleName)
        {
            var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context));

            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            if (manager.IsInRole(user.Id, RoleName))
            {
                manager.RemoveFromRole(user.Id, RoleName);
                ViewBag.ResultMessage = "Role removed from this user successfully !";
            }
            else
            {
                ViewBag.ResultMessage = "This user doesn't belong to selected role.";
            }
            // prepopulat roles for the view dropdown
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;

            return View("ManageUsers");
        }
    }
}

WebApplication13/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" @Html.ActionLink("TATIL ZAMANI", "Index", "Home")></a>
            </div>
            <div style="color:aqua;" class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <div class="nav navbar-nav navbar-right col-md-4">
                    <div class="col-md-3">
                        <div class="dropdown">
                            @if (HttpContext.Current.Session["Culture"].ToString() == "tr")
                            {
                                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Türkçe<span class="caret"></span></button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                        <li>@Html.ActionLink("English", "ChangeCulture", "Home", new { lang = "en", returnurl = this.Request.RawUrl }, null)</li>
                                    </ul>
                            }
                            else
                            {
                                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">ENGLISH<span class="caret"></span></button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                        <li>@Html.ActionLink("Türkçe", "ChangeCulture", "Home", new { lang = "tr", returnurl = this.Request.RawUrl }, null)</li>
                                    </ul>
                            }
                        </div>
                    </div>
                    @*<div class="col-md-9">
                            <div class="input-group">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">@Html.ActionLink(WebApplication11.Resources.HomeText.üyegirisi,"Giris","Uyelers")</button>
                                </span>
                            </div>
                        </div>*@
                    <div class="col-lg-1 col-md-3">
                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                Giriş
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                @if (Session["KullanıcıAdı"] == null)
                                {
                                    <li>@Html.ActionLink(WebApplication13.Resources.HomeText.üyegirisi, "Giris", "Kullanıcı")</li>
                                    <li>@Html.ActionLink(WebApplication13.Resources.HomeText.Yeniuye, "Create", "Kullanıcı")</li>
                                }
                                else
                                {
                                    <li>@Html.ActionLink(WebApplication13.Resources.HomeText.Cıkıs, "Cıkıs", "Kullanıcı")</li>
                                }

                            </ul>
                        </div>
                    </div>
                </div>
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink(WebApplication13.Resources.HomeText.TatilKöyleri, "TatilKoyu", "Home")
                    </li>
                    <li>
                        @Html.ActionLink(WebApplication13.Resources.HomeText.YurtDısıOtelleri, "YurtDısı", "Home")
                    </li>
                    <li>
                        @Html.ActionLink(WebApplication13.Resources.HomeText.ErkenRezervasyonOtelleri, "ErkenRezervasyon", "Home")
                    </li>
                </ul>
            </div>


            <!-- Brand and toggle get grouped for better mobile display -->
            <!-- Collect the nav links, forms, and other content for toggling -->
            <!-- /.navbar-collapse -->
        </div>

        <!-- /.container -->
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row ">
                <div class="col-md-3">&copy;@WebApplication13.Resources.HomeText.Kopyalanamaz.</div>
                <div class="col-md-6">
                    <img src="~/image/facebook_logo.jpg" title="facebook" />
                    <img src="~/image/instagram_logo.jpg" title="instagram" />
                    <img src="~/image/foursquare_logo.jpg" title="foursquare" />
                    <img src="~/image/twitter_logo.jpg" title="twitter" />
                    <img src="~/image/youtube_logo.jpg" title="youtube" />
                </div>
                <div class="col-md-3">
                    @Html.ActionLink(WebApplication13.Resources.HomeText.adminPanel, "/Giris.aspx", "AdminPanel")
                    @Html.ActionLink(WebApplication13.Resources.HomeText.Hakkımızda, "Hakkımızda", "Home")
                    @Html.ActionLink(WebApplication13.Resources.HomeText.RolYönetimi, "Index", "Roles")
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>